version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes: 
      - data:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - mongodb

volumes: 
  data:
  logs:
